sudo apt update
apt install python3-pip
pip install osmium
pip install pandas
pip install geopandas
pip install osmnx
pip install numpy
pip install scikit-learn
pip install jupyterlab
pip install python-dotenv
pip install sqlalchemy
pip install geoalchemy2
pip install psycopg2
